# -*- coding: utf-8 -*-


# langs
iso639 = {
    "aa": "Qafar af",
    "ab": "Аҧсуа ; Apsua ; აფსუა",
    "af": "Afrikaans",
    "ak": "Ákán",
    "sq": "Shqip",
    "am": "አማርኛ (Amarəñña)",
    "ar": "اَلْعَرَبِيَّةُ (al-ʿarabiyyah)",
    "an": "Aragonés",
    "hy": "Հայերեն (Hayeren)",
    "as": "অসমীয়া (Ôxômiya)",
    "av": "Авар мацӏ; اوار ماض (Avar maz)",
    "ae": "Upastawakaēna",
    "ay": "Aymara",
    "az": "Azərbaycan dili; آذربایجان دیلی; Азәрбајҹан дили",
    "bm": "بَمَنَنكَن ;ߓߡߊߣߊ߲ߞߊ߲ (Bamanankan)",
    "ba": "Башҡорт теле; Başqort tele",
    "eu": "Euskara/Euskera",
    "be": "Беларуская мова (Biełaruskaja mova)",
    "bn": "বাংলা (Bāŋlā)",
    "bi": "Bislama",
    "bs": "Босански (Bosanski)",
    "br": "Brezhoneg",
    "bg": "Български (Bulgarski)",
    "my": "မြန်မာစာ (Mrãmācā)",
    "ca": "Català; Valencià",
    "ch": "Finu' Chamoru",
    "ce": "Нохчийн мотт; (Noxçiyn mott)",
    "ny": "Chichewa; Chinyanja",
    "zh": "中文 (Zhōngwén) 汉语; 漢語 (Hànyǔ)",
    "cu": "Славе́нскїй ѧ҆зы́къ",
    "cv": "Чӑвашла (Çăvaşla)",
    "kw": "Kernowek",
    "co": "Corsu",
    "cr": "ᓀᐦᐃᔭᐁᐧᐃᐧᐣ (Nehiyawewin)",
    "hr": "Hrvatski",
    "cs": "Čeština",
    "da": "Dansk",
    "dv": "ދިވެހި (Dhivehi)",
    "nl": "Nederlands",
    "dz": "རྫོང་ཁ་ (Dzongkha)",
    "en": "English",
    "eo": "Esperanto",
    "et": "Eesti keel",
    "ee": "Èʋegbe",
    "fo": "Føroyskt",
    "fj": "Na Vosa Vakaviti",
    "fi": "Suomi",
    "fr": "Français",
    "fy": "Frysk",
    "ff": "Fulah",
    "gd": "Gàidhlig",
    "gl": "Galego",
    "lg": "Luganda",
    "ka": "ქართული (Kharthuli)",
    "de": "Deutsch",
    "el": "Νέα Ελληνικά; (Néa Ellêniká)",
    "kl": "Kalaallisut",
    "gn": "Avañe'ẽ",
    "gu": "ગુજરાતી (Gujarātī)",
    "ht": "Kreyòl ayisyen",
    "ha": "هَرْشٜن هَوْس (halshen Hausa)",
    "he": "עברית‎ (Ivrit)",
    "hz": "Otjiherero",
    "hi": "हिन्दी (Hindī)",
    "ho": "Hiri Motu",
    "hu": "Magyar nyelv",
    "is": "Íslenska",
    "io": "Ido",
    "ig": "ásụ̀sụ́ Ìgbò",
    "id": "bahasa Indonesia",
    "ia": "Interlingua",
    "ie": "Interlingue; Occidental",
    "iu": "ᐃᓄᒃᑎᑐᑦ (Inuktitut)",
    "ik": "Iñupiaq",
    "ga": "Gaeilge",
    "it": "Italiano",
    "ja": "日本語 (Nihongo)",
    "jv": "Javanese",
    "kn": "ಕನ್ನಡ (Kannađa)",
    "kr": "كَنُرِيِه; Kànùrí",
    "ks": "कॉशुर; كأشُر (Kosher)",
    "kk": "Қазақша; Qazaqşa; قازاقشا",
    "km": "ខេមរភាសា; (Khémôrôphéasa)",
    "ki": "Gĩgĩkũyũ",
    "rw": "Ikinyarwanda",
    "ky": "Кыргыз; قىرعىز",
    "kv": "Коми кыв",
    "kg": "Kikongo",
    "ko": "한국어 (Hangugeo) 조선말 (Chosŏnmal)",
    "kj": "Oshikwanyama",
    "ku": "کوردی; Kurdî",
    "lo": "ພາສາລາວ (phasa Lao)",
    "la": "Latinum",
    "lv": "Latviešu",
    "li": "Lèmburgs",
    "ln": "Lingála",
    "lt": "Lietuvių",
    "lu": "Kiluba",
    "lb": "Lëtzebuergesch",
    "mk": "Македонски (Makedonski)",
    "mg": "مَلَغَسِ; Malagasy",
    "ms": "بهاس ملايو (bahasa Melayu)",
    "ml": "മലയാളം (Malayāļã)",
    "mt": "Malti",
    "gv": "Gaelg; Gailck",
    "mi": "reo Māori",
    "mr": "मराठी (Marāṭhī)",
    "mh": "kajin M̧ajel‌̧",
    "mn": "Mongolian",
    "na": "dorerin Naoe",
    "nv": "Diné bizaad; Naabeehó bizaad",
    "nd": "isiNdebele; saseNyakatho; Mthwakazi",
    "nr": "isiNdebele; sakwaNdzundza",
    "ng": "Ndonga",
    "ne": "नेपाली भाषा (Nepālī bhāśā)",
    "no": "Norsk",
    "nb": "Norsk Bokmål",
    "nn": "Norsk Nynorsk",
    "oc": "Occitan; Provençal",
    "oj": "ᐊᓂᔑᓈᐯᒧᐎᓐ (Anishinaabemowin)",
    "or": "ଓଡ଼ିଆ (Odia)",
    "om": "afaan Oromoo",
    "os": "ирон Ӕвзаг (iron Ævzag)",
    "pi": "Pāli",
    "ps": "پښتو (Pax̌tow)",
    "fa": "فارسی (Fārsiy)",
    "pl": "Polski",
    "pt": "Português",
    "pa": "ਪੰਜਾਬੀ; پنجابی (Pãjābī)",
    "qu": "Runa simi; kichwa simi; Nuna shimi",
    "ro": "Română; Ромынэ",
    "rm": "Rumantsch; Rumàntsch; Romauntsch; Romontsch",
    "rn": "Ikirundi",
    "ru": "Русский язык (Russkiĭ âzyk)",
    "se": "Davvisámegiella",
    "sm": "gagana Sāmoa",
    "sg": "yângâ tî Sängö",
    "sa": "संस्कृतम् (Saṃskṛtam)",
    "sc": "Sardu",
    "sr": "Српски (Srpski)",
    "sn": "chiShona",
    "sd": "سنڌي; सिन्धी (Sindhī)",
    "si": "සිංහල (Siṁhala)",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "so": "Soomaali; 𐒈𐒝𐒑𐒛𐒐𐒘; سٝومالِ",
    "st": "Sesotho",
    "es": "Español",
    "su": "Sundanese",
    "sw": "Kiswahili; كِسوَحِيلِ",
    "ss": "siSwati",
    "sv": "Svenska",
    "tl": "Wikang Tagalog",
    "ty": "reo Tahiti",
    "tg": "Тоҷикӣ (Tojikī)",
    "ta": "தமிழ் (Tamiḻ)",
    "tt": "Татар теле; Tatar tele; تاتار تئلئ‎",
    "te": "తెలుగు (Telugu)",
    "th": "ภาษาไทย (Phasa Thai)",
    "bo": "བོད་སྐད་ (Bodskad); ལྷ་སའི་སྐད་ (Lhas'iskad)",
    "ti": "ትግርኛ (Təgrəñña)",
    "to": "lea faka-Tonga",
    "ts": "Xitsonga",
    "tn": "Setswana",
    "tr": "Türkçe",
    "tk": "Türkmençe; Түркменче; تۆرکمنچه",
    "tw": "Twi",
    "ug": "ئۇيغۇر تىلى; Уйғур тили; Uyƣur tili",
    "uk": "Українська (Ukraїnska)",
    "ur": "اُردُو (Urduw)",
    "uz": "Ózbekça; ўзбекча; ئوزبېچه",
    "ve": "Tshivenḓa",
    "vi": "tiếng Việt",
    "vo": "Volapük",
    "wa": "Walon",
    "cy": "Cymraeg",
    "wo": "Wolof",
    "xh": "isiXhosa",
    "ii": "Sichuan Yi, Nuosu",
    "yi": "ייִדיש (Yidiš)",
    "yo": "èdè Yorùbá",
    "za": "話僮 ( Vahcuengh)",
    "zu": "isiZulu"
}


# countries
iso3166 = {
    "AD": "Andorra",
    "AE": "الإمارات العربية المتحدة",
    "AF": "افغانستان",
    "AG": "أنتيغوا وبربودا",
    "AI": "أنغويلا",
    "AL": "Shqipëria",
    "AM": "Հայաստան",
    "AO": "Angola",
    "AQ": "Antártida",
    "AR": "Argentina",
    "AS": "Sāmoa Amelika",
    "AT": "Österreich",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Åland",
    "AZ": "Azərbaycan",
    "BA": "Bosna i Hercegovina",
    "BB": "Barbados",
    "BD": "বাংলাদেশ",
    "BE": "België / Belgique / Belgien",
    "BF": "Burkina Faso",
    "BG": "България",
    "BH": "البحرين",
    "BI": "Uburundi",
    "BJ": "Bénin",
    "BL": "Saint-Barthélemy",
    "BM": "Bermuda",
    "BN": "Negara Brunei Darussalam",
    "BO": "Wuliwya",
    "BQ": "Bonaire, Sint Eustatius en Saba",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BT": "འབྲུག་ཡུལ་",
    "BV": "Bouvetøya",
    "BW": "Botswana",
    "BY": "Беларусь",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "République démocratique du Congo",
    "CF": "République centrafricaine",
    "CG": "République du Congo",
    "CH": "Schweiz / Suisse / Svizzera / Svizra",
    "CI": "Côte d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "中国",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Κύπρος",
    "CZ": "Česko",
    "DE": "Deutschland",
    "DJ": "Djibouti",
    "DK": "Danmark",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "الجزائر",
    "EC": "Ecuador",
    "EE": "Eesti",
    "EG": "مصر‎",
    "EH": "الصحراء الغربية",
    "ER": "ኤርትራ",
    "ES": "España",
    "ET": "ኢትዮጵያ",
    "FI": "Suomi",
    "FJ": "Viti",
    "FK": "Islas Malvinas",
    "FM": "Micronesia",
    "FO": "Føroyar",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "საქართველო",
    "GF": "Guyane",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Kalaallit Nunaat",
    "GM": "Gambia",
    "GN": "Guinée",
    "GP": "Guadeloupe",
    "GQ": "Guinea Ecuatorial",
    "GR": "Ελλάδα",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guåhan",
    "GW": "Guiné-Bissau",
    "GY": "Guyana",
    "HK": "香港",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Hrvatska",
    "HT": "Ayiti",
    "HU": "Magyarország",
    "ID": "Indonesia",
    "IE": "Éire",
    "IL": "יִשְׂרָאֵל",
    "IM": "Isle of Man",
    "IN": "भारत",
    "IO": "British Indian Ocean Territory",
    "IQ": "العراق",
    "IR": "ایران",
    "IS": "Ísland",
    "IT": "Italia",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "الأردن",
    "JP": "日本",
    "KE": "Kenya",
    "KG": "Кыргызстан",
    "KH": "កម្ពុជា",
    "KI": "Kiribati",
    "KM": "Komori",
    "KN": "Saint Kitts and Nevis",
    "KP": "조선민주주의인민공화국",
    "KR": "대한민국",
    "KW": "الكويت",
    "KY": "Cayman Islands",
    "KZ": "Қазақстан",
    "LA": "ລາວ",
    "LB": "لبنان",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "ශ්‍රී ලංකාව",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lietuva",
    "LU": "Lëtzebuerg",
    "LV": "Latvija",
    "LY": "ليبيا",
    "MA": "المغرب",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Crna Gora",
    "MF": "Saint Martin",
    "MG": "Madagasikara",
    "MH": "Marshall Islands",
    "MK": "Северна Македонија",
    "ML": "Mali",
    "MM": "မြန်မာ",
    "MN": "Монгол улс",
    "MO": "澳門",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "موريتانيا",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Maurice",
    "MV": "ދިވެހިރާއްޖޭ",
    "MW": "Malawi",
    "MX": "México",
    "MY": "Malaysia",
    "MZ": "Moçambique",
    "NA": "Namibia",
    "NC": "Nouvelle-Calédonie",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Nederland",
    "NO": "Norge",
    "NP": "नेपाल",
    "NR": "Nauru",
    "NU": "Niuē",
    "NZ": "Aotearoa",
    "OM": "عُمان",
    "PA": "Panamá",
    "PE": "Perú",
    "PF": "Polynésie française",
    "PG": "Papua Niugini",
    "PH": "Pilipinas",
    "PK": "پاکستان",
    "PL": "Polska",
    "PM": "Saint-Pierre-et-Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "فلسطين",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "قطر",
    "RE": "Réunion",
    "RO": "România",
    "RS": "Srbija",
    "RU": "Россия",
    "RW": "Rwanda",
    "SA": "السعودية",
    "SB": "Solomon Islands",
    "SC": "Sesel",
    "SD": "السودان",
    "SE": "Sverige",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "SI": "Slovenija",
    "SJ": "Svalbard og Jan Mayen",
    "SK": "Slovensko",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Sénégal",
    "SO": "Soomaaliya",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "São Tomé e Príncipe",
    "SV": "El Salvador",
    "SX": "Sint Maarten",
    "SY": "سورية",
    "SZ": "Eswatini",
    "TC": "Turks and Caicos Islands",
    "TD": "Tchad",
    "TF": "Terres australes françaises",
    "TG": "Togo",
    "TH": "ประเทศไทย",
    "TJ": "Тоҷикистон",
    "TK": "Tokelau",
    "TL": "Timór Lorosa'e",
    "TM": "Türkmenistan",
    "TN": "تونس",
    "TO": "Puleʻanga Fakatuʻi ʻo Tonga",
    "TR": "Türkiye",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "臺灣",
    "TZ": "Tanzania",
    "UA": "Україна",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Oʻzbekiston",
    "VA": "Santa Sede",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "U.S. Virgin Islands",
    "VN": "Việt Nam",
    "VU": "Vanuatu",
    "WF": "Wallis-et-Futuna",
    "WS": "Samoa",
    "YE": "اليمن",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}


def __language_name__(language_id, country_id=None):
    if (
        (name := iso639.get(language_id)) and
        (country := iso3166.get(country_id))
    ):
        name = f"{name} ({country})"
    return name


def language_name(language):
    return __language_name__(*language.split("-"))
